### ISSUE TITLE
Request to join the team

### ISSUE THREAD

**Issue by ekurniawan** [DiscoverMeteor/DiscoverMeteor_Id#18]
Hi All, My name Erick from Indonesia, I works as a lecturer and IT trainer. I use Meteor platform in our class to teach our students. This is my personal website http://erickkurniawan.net. Can I contribute to this translation project? cc @SachaG

**Comment by SachaG** [comment]
Done :)

**Comment by ekurniawan** [comment]
Thanks, so what's next?

Done :)
